kind: Service
apiVersion: v1
metadata:
  name: appweb1-service
spec:
  type: LoadBalancer
  selector:
    app: appweb1
  ports:
    - port: 80 # Default port for image
      nodePort: 31000
---
kind: Service
apiVersion: v1
metadata:
  name: appweb2-service
spec:
  type: LoadBalancer
  selector:
    app: appweb2
  ports:
    - port: 80 # Default port for image
      nodePort: 31001
---
kind: Service
apiVersion: v1
metadata:
  name: appweb-service
spec:
  type: LoadBalancer
  selector:
    app: appweb
  ports:
    - port: 80 # Default port for image
      nodePort: 31003